<?xml version="1.0" encoding="utf-8"?><Database Name="Tashkil" Class="TashkilDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=Tashkil;Integrated Security=True" SettingsObjectName="Tashkil.Properties.Settings" SettingsPropertyName="TashkilConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Halaka" Member="Halakas">
    <Type Name="Halaka">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MarkazID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Halaka_Masjed" Member="Masjeds" ThisKey="ID" OtherKey="HalakaID" Type="Masjed" />
      <Association Name="Markaz_Halaka" Member="Markaz" ThisKey="MarkazID" OtherKey="ID" Type="Markaz" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Markaz" Member="Markazs">
    <Type Name="Markaz">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Telephone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Markaz_Halaka" Member="Halakas" ThisKey="ID" OtherKey="MarkazID" Type="Halaka" />
      <Association Name="Markaz_Masjed" Member="Masjeds" ThisKey="ID" OtherKey="MarkazID" Type="Masjed" />
    </Type>
  </Table>
  <Table Name="dbo.Masjed" Member="Masjeds">
    <Type Name="Masjed">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="HalakaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MarkazID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Halaka_Masjed" Member="Halaka" ThisKey="HalakaID" OtherKey="ID" Type="Halaka" IsForeignKey="true" />
      <Association Name="Markaz_Masjed" Member="Markaz" ThisKey="MarkazID" OtherKey="ID" Type="Markaz" IsForeignKey="true" />
    </Type>
  </Table>
</Database>